baseURL = "https://txn2.com/"
languageCode = "en-us"
title = "txn2 - OSS Development"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "txn2"
    description = "OSS Development"
    email = ""
    phone = ""
    address = ""
    year = 2020
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = false
    footerEnableFollowme = false
    footerEnableTextWidget = true
    footerEnableFormWidget = false

[[menu.main]]
    name = "github"
    url = "https://github.com/txn2"
    weight = 5

[params.google.analytics]
    trackerID = "UA-118020463-1"
