baseURL = "https://txn2.com/"
languageCode = "en-us"
title = "txn2 - Microservice Applications"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "txn2"
    description = "Microservice Applications"
    email = "cjimti@gmail.com"
    phone = ""
    address = ""
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownload = true
    showClients = true

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5


[params.google.analytics]
    trackerID = "GA-000000000-0"
